### ISSUE TITLE
App crashes when players loses

### ISSUE THREAD

**Issue by chrisK824** [Kelvin-Kwashie/Space-Invaders#1]
When players loses all his lives the app crashes, the following error shown in terminal:

```
➜  Space-Invaders git:(main) python3.11 space_invaders.py
pygame 2.5.2 (SDL 2.28.3, Python 3.11.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
2023-12-31 16:43:05.458 Python[1732:18814] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
Traceback (most recent call last):
  File "/Users/chriskarvouniaris/workspace_local/github/Space-Invaders/space_invaders.py", line 257, in <module>
    main_manu()
  File "/Users/chriskarvouniaris/workspace_local/github/Space-Invaders/space_invaders.py", line 254, in main_manu
    main()
  File "/Users/chriskarvouniaris/workspace_local/github/Space-Invaders/space_invaders.py", line 195, in main
    if lost_font > FPS *3:
       ^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'pygame.font.Font' and 'int'
```

not sure what is the logic there, so don't know what that condition is supposed to be doing, but the comparison is not allowed

**Comment by Kelvin-Kwashie** [comment]
I will fix that as soon as possible

**Comment by Kelvin-Kwashie** [comment]
It has fixed
